# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65bff14ab7838353a1b502d666f8925dff54f4e487314eb540bf56f7f6888a3e27a5def61095670383c1c4782b3a57487b0611b93d2dc2712d50fc8ac5c9a3af

test:
  secret_key_base: 91e936a9c024257f973fa6a9896d4f1f10c9b0723c4f432039a10a04a38045a0075e9fcfd9ca3bb9bc450258a5736a1c2a743df3997b284bbd911aafc26d5b86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
